export const API_URLS = {
    BASE_URL_GDS: 'http://gds-stg.ticketsimply.co.in/',
    BASE_URL: 'http://localhost:5086/api',
    KEY: 'TSSACPAPI73263707',
    CITIES: 'gds/api/cities.json',
    CITY_PAIRS: '/gds/api/city_pairs.json',
    STAGES: '/gds/api/stages.json',
    SCHEDULES: '/gds/api/schedules/:origin_id/:destination_id/:travel_date.json',
    // OPERATOR_SCHEDULES: '/gds/api/operator_schedules/:travel_id/:travel_date.json',
    OPERATOR_SCHEDULES: 'gds/api/operator_schedules',
    SCHEDULE: '/gds/api/schedule/:schedule_id.json',
    AVAILABILITIES: '/gds/api/availabilities/:origin_id/:destination_id/:travel_date.json',
    AVAILABILITY: '/gds/api/availability/:schedule_id.json',
    TENTATIVE_BOOKING: '/gds/api/tentative_booking/:schedule_id.json',
    CONFIRM_BOOKING: '/gds/api/confirm_booking/ticket_number.json?api_key=apikey',
    BOOKING_DETAILS: '/gds/api/booking_details.json?pnr_number=<ticket_number>&agent_ref_number=<ag_ref_num>',
    CAN_CANCEL: '/gds/api/can_cancel.json?ticket_number=<ticket_number>&seat_numbers=<seat_numbers>',
    CANCEL_BOOKING: '/gds/api/cancel_booking.json?ticket_number=<ticket_number>&seat_numbers=<seat_numbers>',
    TRANSACTION_LOG: '/gds/api/transaction_log.json?trans_date=<trans_date>',
    GET_BALANCE: '/gds/api/get_balance.json?travel_id=<travel_id>',
    POST_USER:'/api/User/PostUser',
    POST_BUS_PACKAGE:'/Package/Postpackage',
    Get_Itinerary_List:'/PkgItinerary/GetpkgItinerary',
    POST_ITINERARY:'/PkgItinerary/SavepkgItinerary',
    Get_HIGHLIGHTS:'/PkgHighlight/Getpkghighlight',
    POST_HIGHLIGHTS:'/PkgHighlight/SavePostpackage',
    GET_IMP_NOTES:'/PkgImpNotes/GetPkgImpNotes',
    GET_PACKAGE_SERVICE:'/ServiceDtls/GetpkgImageDtlByPackageID',
    POST_IMP_NOTES:'/PkgImpNotes/SavePkgImpNotes',
    GET_INCLUDED_LIST:'/PkgInclude/GetpkgInclude',
    POST_INCLUDED_LIST:'/PkgInclude/SavepkgInclude',
    save_PACKAGE_IMG_DETAILS:'/PkgImageDtls/SavePkgImageDtls',
    POST_SCHEDULE_PRICING:'/ServiceDtls/SaveServiceDtls',
    GetBusBookingSeat:'/BusBookingSeat/GetBusBookingSeat',
    SIGNUP:'/User/PostUser',
    SIGNIN:'/Auth/login',
    getUser:'/User/GetUserByID',
    getCountries:'/Countries/GetCountries',
    getStates:'/State/GetState',
    getStatesByCountryID:'/State/GetStateByCountry',
    GetpackageDetails:'/Package/GetpackageDetails',
    add_Attachment:'/Attachment/addFile',
    delete_Attachment:'/Attachment/Delete',
    get_AttachmentID:'/Attachment/GetFileData',
    get_PackageDetailByID:'/Package/GetpackageDtlByID',
    get_PackageHighlightByID:'/PkgHighlight/GetpkghighlightByPackageID',
    get_GetpkgImageDtls:'/PkgImageDtls/GetpkgImageDtls',
    get_ServiceDtlsByID:'/ServiceDtls/GetServiceDtlsByID',
    get_WalletTransactionByID:'/WalletTransaction/GetWalletTransactionByID',
    save_Wallet:'/Wallet/SaveWallet',
    save_WalletTransaction:'/WalletTransaction/SaveWalletTransaction',
    get_WalletTransaction:'/WalletTransaction/GetWalletTransaction',
    get_WalletByUserID:'/Wallet/GetWallet',
    post_Phonepe:'/PhonePe/CreateOrder',
    post_Payment:'/Payment/SavePayment',
    get_Payment : '/Payment/GetPayment',
    get_wallet_BYID:'/Wallet/GetWalletByID',
    
};